blogapp/urls.py
from django.urls import path
from . import views

app_name='blogapp'

urlpatterns = [ 
    path('blog/', views.blog, name='blog'),
    path('blog_details/<int:pk>', views.blog_details, name='blog_details'),
]

contactapp/urls.py
from django.urls import path
from .import views

app_name='contactapp'

urlpatterns = [
    path('', views.contact, name='contact'),
    # path('about/', views.about, name='about'),
    # path('team/', views.team, name='team'),
 
]
      

event_management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeapp.urls')),
    path('contact/', include('contactapp.urls')),
    path('event/', include('eventsapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('__debug__/', include('debug_toolbar.urls')),
   
]

if settings.DEBUG:
    #urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

eventsapp/urls.py
from django.urls import path
from . import views

app_name='eventsapp'

urlpatterns = [ 
    path('', views.packages, name='packages'), 
]

homeapp/urls.py
from django.urls import path
from . import views

app_name='homeapp'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('about/', views.about, name='aboutpage'),
    path('gallery/', views.gallery, name='gallerypage'),
    path('team/', views.team, name='teampage'),

]

templates/global/footer.html
{% load static %}

{% block content %}

<!--===================== FOOTER =====================-->
<footer>
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-4"> 
				<a href="{% url 'homeapp:homepage' %}" >
					<img src="{% static 'img/logo1.png' %}" alt="logo" class="logo">
					
				</a> 
				<div class="footer-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</div>
				<ul class="soc-link">
					<li><a target="_blank" href="https://www.facebook.com/rovadex"><i class="fab fa-facebook-f"></i></a></li>
					<li><a target="_blank" href="https://twitter.com/RovadexStudio"><i class="fab fa-twitter"></i></a></li>
					<li><a target="_blank" href="https://www.instagram.com/rovadex"><i class="fab fa-instagram"></i></a></li>
					<li><a target="_blank" href="https://www.youtube.com"><i class="fab fa-youtube"></i></a></li>
				</ul>
			</div>
			<div class="col-12 col-sm-6 col-md-4">
				<h6>Contacts</h6>
				<ul class="footer-contacts">
					<li>
						<i class="fas fa-map-marker-alt"></i>
						<a href="#">Uttara <br>Dhaka-1230</a>
					</li>
					<li>
						<i class="fa fa-phone" aria-hidden="true"></i>
						<a href="tel:01921-648721">01921-648721</a>
					
					</li>
					<li>
						<i class="fa fa-envelope" aria-hidden="true"></i>
						<a href="mailto:dreamloading@gmail.com">dreamloading@gmail.com</a>
					</li>
				</ul>
			</div>
			<div class="col-12 col-sm-6 col-md-4 insta-list-cover">
				<h6>Some of our capture </h6>
				<ul class="insta-list">

					{% for img in  footer_gallerys %}
					<li><a target="_blank" href="{{img.image.url}}">
						<img class="lazy" src="{{img.image.url}}" alt="social" loading="lazy"></a></li>
					{% endfor %}
					
				</ul>
			</div>
		</div>
	</div>
	<div class="footer-bottom">
		<div class="container">
			<div class="row">
				<div class="col-12 col-md-12" style="text-align:center;"><div class="copyright">© 2022. All Rights Reserved
					by:Dreamloadingbd | Design & Developed By: <a target="_blank" href="https://dhakasolution.com">Dhaka Solution</a>.</div></div>
				<div class="col-8">
					
				</div>
			</div>
		</div>
	</div>
</footer>
<!--=================== FOOTER END ===================-->

<!--===================== TO TOP =====================-->
<a class="to-top" href="#home">
	<i class="fa fa-chevron-up" aria-hidden="true"></i>
</a>
<!--=================== TO TOP END ===================-->

{% endblock %}

templates/global/navbar.html
{% load static %}

{% block content %}


<style>
/* 
.navbar-brand {
    background: url(../../static/img/logo3.png);
    width:220px;
    height:65px;
    margin-left:5px;
} */
@media only screen and (max-width:775px) {
    .logo {
        /* height: 150;
        width:70px; */
		height: 250;
        width:170px;
    }
}
</style>


	<!--===================== HEADER =====================-->

	<header class="header-two">
		<a href="{% url 'homeapp:homepage' %}" class="nav-btn">
			<span></span>
			<span></span>
			<span></span>
		</a>
		<div class="header-two-top">
			<div class="container">
				<div class="row align-items-center">
					<div class="col-12 col-md-6 col-lg-3 logo-two-cover">
						<a href="{% url 'homeapp:homepage' %}" >
							<img src="{% static 'img/logo1.png' %}" alt="logo" class="logo" loading="lazy">
							
						</a> 
						<!-- <a class="navbar-brand" href="/"></a> -->

					</div>
					<div class="col-3 header-top-info">
						<ul class="header-two-phone header-cont">
							<li><a href="tel:01921-648721"><i class="fas fa-phone"></i>01921-648721</a></li>
						</ul>
					</div>
					<div class="col-3 header-top-info">
						<ul class="header-two-adr header-cont">
							<li><a href="{% url 'contactapp:contact' %}"><i class="fas fa-map-marker-alt"></i>Uttara ,Dhaka-1230</a></li>
						</ul>
					</div>
					<div class="col-12 col-sm-6 col-lg-3 header-two-btn">
						<a href="{% url 'eventsapp:packages' %}" class="btn">show all packagess</a>
					</div>
				</div>
			</div>
		</div>
		<div class="header-menu header-menu-two">
			<div class="container">
				<div class="row">
					<div class="col-10">
						<nav class="nav-menu">
							<ul class="nav-list">
								<li><a href="{% url 'homeapp:homepage' %}">Home </a></li>
								<li><a href="{% url 'homeapp:aboutpage' %}">About us</a></li>       
								<li><a href="{% url 'homeapp:gallerypage' %}">Gallery</a></li>
								<li><a href="{% url 'blogapp:blog' %}">News</a></li>
								<li><a href="{% url 'homeapp:teampage' %}">Teams</a></li>
								<li><a href="{% url 'eventsapp:packages' %}">Packages </a></li>
								<li><a href="{% url 'contactapp:contact' %}">Contacts</a></li>
							</ul>
						</nav>
					</div>
					<div class="col-2">
						<div class="header-two-search">
							<div class="header-search-icon">
								<i class="fas fa-search"></i>
							</div>
							<form action="#">
								<input type="search" name="search" placeholder="Search">
								<button class="btn-search" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	<!--=================== HEADER END ===================-->

{% endblock %}

templates/global/thankyou.html
 {% extends 'base.html' %}
  {% load static %}
  {% block content %}


<section class="error-page section">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 offset-lg-12 col-12 thanku" >
				<!-- Error Inner -->
				<div class="error-inner">
					<h1>Thank you!</h1>
					<h1><span>We will reach you soon.!</span></h1>
						
						<button class="btn mt-3 mb-3" type="submit"><a href="{% url 'homeapp:homepage' %}">Back to homepage</a></button>
				</div>
				<!--/ End Error Inner -->
			</div>
		</div>
	</div>
  </section>


{% endblock %}